# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import world_data_pb2 as world__data__pb2


class AIEconomistStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorldMap = channel.unary_unary(
                '/AIEconomist/GetWorldMap',
                request_serializer=world__data__pb2.Time.SerializeToString,
                response_deserializer=world__data__pb2.MapData.FromString,
                )
        self.SendWorldMap = channel.unary_unary(
                '/AIEconomist/SendWorldMap',
                request_serializer=world__data__pb2.MapData.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AIEconomistServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWorldMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWorldMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIEconomistServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorldMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorldMap,
                    request_deserializer=world__data__pb2.Time.FromString,
                    response_serializer=world__data__pb2.MapData.SerializeToString,
            ),
            'SendWorldMap': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWorldMap,
                    request_deserializer=world__data__pb2.MapData.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AIEconomist', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIEconomist(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWorldMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIEconomist/GetWorldMap',
            world__data__pb2.Time.SerializeToString,
            world__data__pb2.MapData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendWorldMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIEconomist/SendWorldMap',
            world__data__pb2.MapData.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
